"""Fail if a teaching notebook's published render is older than its source.

The versioned source of each teaching notebook is ``notebooks/NN_*.py`` (a jupytext
percent script); the published render shown on the docs site is the pre-executed
``docs/notebooks/NN_*.ipynb``, regenerated by ``make docs-notebooks`` (ADR-0015).
Because that re-render is a **manual** step, editing a ``.py`` without re-rendering
leaves the committed ``.ipynb`` stale — the site would show outputs from old code.

This check compares the last-commit timestamp of each source/render pair and fails
if the source is newer, so CI (and a local run) flags a forgotten re-render.

**Caveat:** the signal is git-commit timestamps, not content. A ``.py`` edit that does
not affect output (a comment, a rename) still trips it — the fix is a harmless
``make docs-notebooks``. This deliberately errs toward reminding you to re-render.

Usage:
    python scripts/check_notebook_render_fresh.py    # exit 1 if any render is stale
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SOURCE_DIR = _REPO_ROOT / "notebooks"
_RENDER_DIR = _REPO_ROOT / "docs" / "notebooks"


def _last_commit_timestamp(path: Path) -> int | None:
    """Return the Unix timestamp of the last commit touching ``path``.

    Args:
        path: Repo-relative or absolute path to a tracked file.

    Returns:
        The committer Unix timestamp, or ``None`` if git records no commit for the
        file (untracked, or history too shallow — CI must checkout with full depth).
    """
    result = subprocess.run(
        ["git", "log", "-1", "--format=%ct", "--", str(path)],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    out = result.stdout.strip()
    return int(out) if out else None


def find_stale_renders() -> list[tuple[str, str]]:
    """Find teaching notebooks whose published render predates its source.

    Returns:
        A list of ``(source_name, reason)`` for each stale or unresolved pair, in
        notebook order. Empty when every render is at least as new as its source.
    """
    stale: list[tuple[str, str]] = []
    for source in sorted(_SOURCE_DIR.glob("[0-9]*.py")):
        render = _RENDER_DIR / f"{source.stem}.ipynb"
        if not render.exists():
            stale.append(
                (
                    source.name,
                    f"no published render at {render.relative_to(_REPO_ROOT)}",
                )
            )
            continue
        source_ts = _last_commit_timestamp(source)
        render_ts = _last_commit_timestamp(render)
        if source_ts is None or render_ts is None:
            stale.append(
                (
                    source.name,
                    "no git history for the pair (checkout with fetch-depth: 0)",
                )
            )
        elif source_ts > render_ts:
            stale.append(
                (source.name, "source committed after its render — re-render needed")
            )
    return stale


def main() -> int:
    """Report stale notebook renders and return a process exit code."""
    stale = find_stale_renders()
    if not stale:
        print("All teaching notebook renders are up to date with their sources.")
        return 0
    print("Stale teaching notebook render(s) detected:\n")
    for name, reason in stale:
        print(f"  - {name}: {reason}")
    print(
        "\nFix: run `make docs-notebooks` to regenerate docs/notebooks/, then commit."
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
